### ISSUE TITLE
Product buttons don't add the product button to the cart

### ISSUE THREAD

**Issue by Chelseavb314** [Foo-Tang/ecomm#3]
Location:  app/views/products/_product.html.erb

Lines: 18 - 29

The buttons to add and remove from the cart don't submit to the cart.
They instead navigate the user to the products#show page, even though their url is assigned to the cart_index_path (create) or the cart_path(product) *delete.

![image](https://github.com/Foo-Tang/ecomm/assets/55150598/9644aa51-961f-4020-a444-1ff49547c79f)

**Comment by Foo-Tang** [comment]
The whole box was a link to the product page so it overrides the button. Moved the link to the title and price.
